# Generated by Django 5.1.1 on 2024-12-09 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specie_horta', models.CharField(blank=True, max_length=50, null=True)),
                ('color_horta', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=50)),
                ('password_user', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HortaNutriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutriente_name', models.CharField(max_length=50)),
                ('horta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hortas', to='app_create_account.horta')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_job', models.CharField(blank=True, max_length=50, null=True)),
                ('position_job', models.CharField(blank=True, max_length=50, null=True)),
                ('salary_job', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='app_create_account.user')),
            ],
        ),
        migrations.AddField(
            model_name='horta',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horta', to='app_create_account.user'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(blank=True, max_length=50, null=True)),
                ('number_document', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='app_create_account.user')),
            ],
        ),
    ]
